config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#top"
  resources :books
  resources :users, only: [:show, :index, :edit, :update]
  get '/home/about', to: 'home#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
has_one_attached :image
  belongs_to :user
  validates :title, presence: true
  validates :body, length: { maximum: 200}
  validates :body, presence: true

  def get_image
    if image.attached?
      image
    else
      'no_image.jpg'
    end
  end

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image

  has_many :books, dependent: :destroy

  validates :name, presence: true
  validates :name, length: { minimum: 2, maximum: 20}
  validates :name, uniqueness: true
  validates :introduction, length: {maximum: 50}

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    flash[:notice] = "Signed in successfully."
    user_path(resource.id)
  end

  def after_sign_out_path_for(resource)
    flash[:notice] = "Signed out successfully."
    home_about_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book = Book.new
    @user = current_user
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_new = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      flash[:notice] = "You have created book failed."
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
     if @book.update(book_params)
        flash[:notice] = "You have updated book successfully."
        redirect_to book_path(@book.id)
     else
        flash[:notice] = "You have updated book failed."
        render :edit
     end
  end
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to '/books'
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
  
  def is_matching_login_user
    book = Book.find(params[:id])
    user_id = book.user_id
    login_user_id = current_user.id
    if(user_id != login_user_id)
      redirect_to '/books'
    end
  end
end

app/controllers/concerns/application_controller.rb
class BooksController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end

  private

  def books_params
    params.require(:book).permit(:name, :body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    
  end
  
  def about
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h2>Editing Book</h2>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book do |f| %>
  <label for="inputTitle">Title</label>
  <%= f.text_field :title, autofocus: true, id:"inputTitle", placeholder:"Title"%>
  <label for="inputOpinion">Opinion</label>
  <%= f.text_area :body, placeholder: "inputOpinion", placeholder:"Opinion" %>
  <%= f.submit "Update Book" %>
<% end %>

<h3>
  <% if @book.user == current_user %>
    <%= link_to "Show", book_path(@book) %>
  <% end %>
  <% if @book.user == current_user %>
    <%= link_to "Back", "/books" %>
  <% end %>
</h3>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= render 'users/user', user: @user ,book: @book %>
<h1>Books</h1>
<% @books.each do |book| %>
  <%= link_to user_path(book.user.id) do %>
  <%= image_tag book.user.get_profile_image(100,100) %>
  <% end %>
  <%= link_to book.title, book_path(book.id) %>
  <%= book.body %>
<% end %>

app/views/books/show.html.erb
<%= flash[:notice] %>
<%= render 'users/user', user: @user, book: @book_new %>
<h1>Book detail</h1>
<%= link_to (@book.user) do %>
  <%= image_tag @book.user.get_profile_image(100,100) %> </br>
  <%= @book.user.name %>
<% end %>
<%=link_to @book.title, book_path(@book.id) %>
<%= @book.body %>
<% if @book.user == current_user %>
  <%= link_to "Edit", edit_book_path(@book.id), %>
<% end %>
<% if @book.user == current_user %>
  <%= link_to "Destroy", book_path(@book), method: :delete, %>
<% end %>

app/views/home/about.html.erb
<h1>Welcome to Bookers!</h1>

app/views/home/top.html.erb
<%= flash[:notice] %>
<h1>Welcome to Bookers !!</h1>
<p>In Bookers,</p>
<P>you can share and exchange your opinions , inpressions , and emotions</P>
<p>about various books!</p>
<%= link_to 'Log in', "/users/sign_in" %>
<%= link_to 'Sign up', "/users/sign_up" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <span>Bookers</span>
      <li>
        <%= link_to "Home", root_path %>
      </li>
      <% if user_signed_in? %>
      <li>
         <%= link_to "Users", users_path %>
      </li>
      <li>
        <%= link_to "Books", books_path %>
      </li>
      <li>
        <%= link_to "Log out", destroy_user_session_path, method: :delete %>
      </li>
      <% else %>
      <li>
        <%= link_to "About", home_about_path %>
      </li>
      <li>
        <%= link_to"Sign up", new_user_registration_path %>
      </li>
      <li>
        <%= link_to "Log in",new_user_session_path %>
      </li>
      <% end %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/users/_user.html.erb
<h1>User info</h1>
    <%= image_tag user.get_profile_image(100,100) %>
  <p>name：<%= user.name %></p>
  <p>introduction : <%= user.introduction %></p>
    <%= link_to edit_user_path(user) %>

<h1>New book</h1>
  <%= form_with model: book do |f| %>
  <h4>Title</h4>
    <%= f.text_field :title %>
  <h4>Opinion</h4>
    <%= f.text_area :body %>
    <%= f.submit 'Create Book' %>
  <% end %>

app/views/users/edit.html.erb
  <%= flash[:notice] %>
<h2>User info</h2>
<% if @user.errors.any? %>
  <%= @user.errors.count %>件のエラーが発生しました
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @user do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
  <label for="inputImage">Image</label>
  <%= f.file_field :profile_image, placeholder: "画像", accept: "image/*" %>
  <label for="inputIntroduction">Introduction</label>
  <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction" %>
  <%= f.submit "Update User" %>
<% end %>

app/views/users/index.html.erb
<%= render 'user', user: @user, book: @book %>
<h1>Users</h1>
<% @users.each do |user| %>
  <%= link_to user_path(user.id) do %>
  <%= image_tag user.get_profile_image(100,100) %>
  <%= user.name %>
  <%= link_to 'Show', user %>
  <% end %>
<% end %>

app/views/users/show.html.erb
<%= flash[:notice] %>
<%= render 'user', user: @user, book: @book %>
<h1>Books</h1>
<% @books.each do |book| %>
  <%= link_to user_path(@user.id) do %>
  <%= image_tag book.user.get_profile_image(100,100) %>
  <% end %>
  <%=link_to book.title, book_path(book.id) %>
  <%= book.body %>
<% end %>